### ISSUE TITLE
IP Address issue

### ISSUE THREAD

**Issue by farazirfan47** [stefanzweifel/screeenly#116]
I am taking screenshot from http://www.overstock.com. This site changes currency according to your IP address, currently I am crawling prices in USD by using US IP but when I take screenshot using screenly it shows me Singapore version of site and all prices are in SGD, that's because of leaking screenly IP address. Please let me know how can I explicitly configure US IP in screenly so that my crawl price and screenshot price will be same. Thanks

**Comment by stefanzweifel** [comment]
Hi,

Sorry that you don't see USD prices in the screenshot. screeenly.com is currently hosted on a single DigitalOcean Droplet in the FRA1 region in Germany. There are no US Droplets.

To make this work I would have to add a new API configuration to allow users to set the server-region. In addition I would have to split the API-part of the app from the code which takes screenshots and distribute the "take screenshot code" on different servers around the world.

screeenly.com is a free service and I want to keep it free. The mentioned changes would mean a lot of work for me and a bigger server-bill at the end of the month. I'm also currently involved in other projects and don't have the energy to invest into screeenly.

I've written a [self hosting guide](https://github.com/stefanzweifel/screeenly/wiki/Requirements-and-Install) in our wiki. I would suggest you deploy your own version of screeenly on a US server or use a service that supports that feature.

Sorry for the bad news about this issue, but I hope this clarifies the problem for you.
