### ISSUE TITLE
What about SlimeJS?

### ISSUE THREAD

**Issue by peterbrinck** [stefanzweifel/screeenly#13]
I've read up on PhantomJS and web font, and I've found someone recommending SlimeJS, which is almost the same, but instead of WebKit, it uses Firefox' Gecko engine

http://slimerjs.org/

**Comment by stefanzweifel** [comment]
Thanks for the suggestion. I will definitely test it.

**Comment by stefanzweifel** [comment]
Haven't found a decent PHP API Wrapper.
