### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by marcelklehr** [stefanzweifel/screeenly#152]
Hey,

I got the service to work now. It works splendidly. One thing that bothers me a little is that I can't access it using https at the moment :/ Are there any plans to support that?

**Comment by stefanzweifel** [comment]
Yeah, that's something I really wan't to fix.
When I started screeenly, the app was hosted on a cheap shared hosting server and there was no Let's Encrypt.
Then I switched to Digital Ocean and Forge…

When a SSL-Certificate is activated on Forge, all HTTP traffic is automatically redirected to HTTPS. This would break all old API clients. 🙄 

I think the best solution would be providing a second, secured URL (like `https://secure.screeenly.com`) and deprecating the old HTTP URL. I probably would have to write to all users, that at a certain date all HTTP traffic is redirected to HTTPs and that they should update their API clients.

**Comment by stefanzweifel** [comment]
Quick update: I've created [secure.screeenly.com](https://secure.screeenly.com/). It's a copy of the app hosted on [screeenly.com](https://screeenly.com) and it connects to the same database. 

Point your API client to the new URL to send your request over HTTPS. I will think about a switching the main domain to HTTPS over the coming days.

**Comment by stefanzweifel** [comment]
(Oh and you can't use the Github Sign In Button on the new subdomain, as I don't want to setup a new Github app)

**Comment by marcelklehr** [comment]
Awesome!

The github sign in is regrettable. Isn't there a way to change the URL of a github app?

**Comment by stefanzweifel** [comment]
I can change the URL, but that would break the Github Sign In flow on screeenly.com. I could create a second Github app called "Screeenly", but that's also not desirable.

I will update the app/wiki to include the new URL and would like to close this issue, if you're fine with the current solution.

**Comment by marcelklehr** [comment]
Yep, that's fine for now.
