### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by amiller911** [stefanzweifel/screeenly#239]
Hi.

I get error 404 in page site.com/try, faq and etc. in production. But in local site.com/try, faq and other work.

How to fix its problem?

Thank you.

**Comment by stefanzweifel** [comment]
Well, can you give me a bit more information?

- How have you deployed the application? 
  - Did you run `composer install` and `npm install` on your production server?
- What web server are you using? 
  - Is your webroot correctly set up?

**Comment by amiller911** [comment]
I have project in Mac OS (Local). All page work.

For deploy to server i just make archive from my laptop.

Yes i have _npm install_ and _composer install_

My webroot in production server.

> server {
	server_name screener.space www.screener.space;
	ssl_certificate "/var/www/httpd-cert/www-root/screener.space.crt";
	ssl_certificate_key "/var/www/httpd-cert/www-root/screener.space.key";
	ssl_ciphers EECDH:+AES256:-3DES:RSA+AES:!NULL:!RC4;
	ssl_prefer_server_ciphers on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_dhparam /etc/ssl/certs/dhparam4096.pem;
	charset off;
	index index.php index.html;
	disable_symlinks if_not_owner from=$root_path;
	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/screener.space/*.conf;
	access_log /var/www/httpd-logs/screener.space.access.log;
	error_log /var/www/httpd-logs/screener.space.error.log notice;
	ssi on;
	set $root_path /var/www/www-root/data/www/screener.space/public;
	root $root_path;
	listen 5.253.60.23:443 ssl;
	location / {
		location ~ [^/]\.ph(p\d*|tml)$ {
			try_files /does_not_exists @php;
		}
	}
	location @php {
		fastcgi_index index.php;
		fastcgi_param PHP_ADMIN_VALUE "sendmail_path = /usr/sbin/sendmail -t -i -f webmaster@screener.space";
		fastcgi_pass unix:/var/www/php-fpm/www-root.sock;
		fastcgi_split_path_info ^((?U).+\.ph(?:p\d*|tml))(/?.+)$;
		try_files $uri =404;
		include fastcgi_params;
	}
}

Why i get error in production? In local in my laptop all work.

**Comment by stefanzweifel** [comment]
> set $root_path /var/www/www-root/data/www/name.space/public;

Maybe this has to be updated to the actual folder path, where you've uploaded the project?


This is the NGINX configuration, I'm currently using for hosting screeenly.com. (I'm using [Laravel Forge](http://forge.laravel.com))

```nginx
# FORGE CONFIG (DOT NOT REMOVE!)
include forge-conf/screeenly.com/before/*;

server {
    listen 80;
    listen [::]:80;
    server_name screeenly.com;
    root /home/forge/screeenly.com/public;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!3DES';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DOT NOT REMOVE!)
    include forge-conf/screeenly.com/server/*;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    
    access_log off;
    error_log  /var/log/nginx/screeenly.com-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

# FORGE CONFIG (DOT NOT REMOVE!)
include forge-conf/screeenly.com/after/*;
```

Could you also please check the [Installation Guide](https://laravel.com/docs/5.8#configuration) from Laravel and see if your server supports everything Laravel needs?

**Comment by amiller911** [comment]
> > set $root_path /var/www/www-root/data/www/name.space/public;
> 
> Maybe this has to be updated to the actual folder path, where you've uploaded the project?
> 
> This is the NGINX configuration, I'm currently using for hosting screeenly.com. (I'm using [Laravel Forge](http://forge.laravel.com))
> 
> ```nginx
> # FORGE CONFIG (DOT NOT REMOVE!)
> include forge-conf/screeenly.com/before/*;
> 
> server {
>     listen 80;
>     listen [::]:80;
>     server_name screeenly.com;
>     root /home/forge/screeenly.com/public;
> 
>     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>     ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!3DES';
>     ssl_prefer_server_ciphers on;
>     ssl_dhparam /etc/nginx/dhparams.pem;
> 
>     add_header X-Frame-Options "SAMEORIGIN";
>     add_header X-XSS-Protection "1; mode=block";
>     add_header X-Content-Type-Options "nosniff";
> 
>     index index.html index.htm index.php;
> 
>     charset utf-8;
> 
>     # FORGE CONFIG (DOT NOT REMOVE!)
>     include forge-conf/screeenly.com/server/*;
> 
>     location / {
>         try_files $uri $uri/ /index.php?$query_string;
>     }
> 
>     location = /favicon.ico { access_log off; log_not_found off; }
>     location = /robots.txt  { access_log off; log_not_found off; }
>     
>     access_log off;
>     error_log  /var/log/nginx/screeenly.com-error.log error;
> 
>     error_page 404 /index.php;
> 
>     location ~ \.php$ {
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
>         fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
>         fastcgi_index index.php;
>         include fastcgi_params;
>     }
> 
>     location ~ /\.(?!well-known).* {
>         deny all;
>     }
> }
> 
> # FORGE CONFIG (DOT NOT REMOVE!)
> include forge-conf/screeenly.com/after/*;
> ```
> 
> Could you also please check the [Installation Guide](https://laravel.com/docs/5.8#configuration) from Laravel and see if your server supports everything Laravel needs?

Its work now. Thank you.

But when i want make Screenshot

I get error:
`Something went wrong capturing this website. Is it a Javascript heavy site or loads lots of external content? If you think this is an error contact us.`

Why i get its error?

**Comment by stefanzweifel** [comment]
I assume you're using the `/try` URL? The error usually comes from the fact the Google Chrome has not been properly installed.
Screeenly uses Google Chrome to take Screenshots.

[The wiki](https://github.com/stefanzweifel/screeenly/wiki/Requirements-and-Install) has a description on how you can install Google Chrome on an Ubuntu server. The underlying package screeenly uses has more information about this: [Link](https://github.com/spatie/browsershot#requirements)

I'm closing this issue now, as the original error has been fixed.
