### ISSUE TITLE
Use Laravel 5.2 rate limit middleware

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/screeenly#31]
See: https://mattstauffer.co/blog/api-rate-limiting-in-laravel-5-2

**Comment by bikker** [comment]
@stefanzweifel can we limit api requests per key? like suppose we only want 10 requests an hour etc.

**Comment by stefanzweifel** [comment]
@bikker Such a feature is currently not built into screeenly. Laravel, the framework we use under the hood, supports such feature since v5.6: https://laravel-news.com/laravel-5-6-dynamic-rate-limiting

It would require and update to the database tables. I'm currently quite busy with other projects, so I won't update the project to include this.

The amount of requests per minute is currently hardcoded to 60.
Here's the relevant code: https://github.com/stefanzweifel/screeenly/blob/master/app/Http/Kernel.php#L41
