### ISSUE TITLE
Create new api_key fails

### ISSUE THREAD

**Issue by hadogenes** [stefanzweifel/screeenly#313]
When I try to add new api_key i get error:

> "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "8MARLdT6gVayOaSQ8YI9Bn5nRdSfqljbnD4iVBTUFPjWXDXvGj" (SQL: select * from "api_keys" where "api_keys"."id" = 8MARLdT6gVayOaSQ8YI9Bn5nRdSfqljbnD4iVBTUFPjWXDXvGj limit 1)"

I'm using postgresql

**Comment by stefanzweifel** [comment]
Hi,

Unfortunately I've never used postgresql in the past and can't really help you with this issue.

As screeenly uses Laravel under the hood I can only point you to the [database docs](https://laravel.com/docs/5.8/database).

I can also point you to the code which executes above query:
https://github.com/stefanzweifel/screeenly/blob/2187309ecf80e358de3043875c642e10e5d4c94f/modules/Screeenly/Models/ApiKey.php#L36-L45

And this is the database migration which creates the database table:
https://github.com/stefanzweifel/screeenly/blob/2187309ecf80e358de3043875c642e10e5d4c94f/database/migrations/2015_07_08_211146_create_api_keys_table.php#L15-L23

---

What is really weird is the WHERE clause. That should be `api_keys.key` and not `api_keys.id`.

```sql
select * 
from "api_keys" 
where "api_keys"."id" = 8MARLdT6gVayOaSQ8YI9Bn5nRdSfqljbnD4iVBTUFPjWXDXvGj
limit 1
```

This should be the query

```sql
select * 
from "api_keys" 
where "api_keys"."key" = 8MARLdT6gVayOaSQ8YI9Bn5nRdSfqljbnD4iVBTUFPjWXDXvGj 
limit 1
```

I've updated the code a bit in https://github.com/stefanzweifel/screeenly/commit/2187309ecf80e358de3043875c642e10e5d4c94f. Maybe you can update your copy and try it again?

**Comment by hadogenes** [comment]
Thanks it works now
