### ISSUE TITLE
Redis connection error

### ISSUE THREAD

**Issue by hadogenes** [stefanzweifel/screeenly#315]
It looks like you have forgotten to add _predis/predis_ to composer dependencies
when I run _composer require predis/predis_ it starts working

**Comment by stefanzweifel** [comment]
Feel free to open a PR for this.

**Comment by stefanzweifel** [comment]
Can you maybe describe, why **you** needed redis in your installation? I guess for the caching driver?

Haven't looked through the code in a long time, but I don't think there screeenly caches anything.

**Comment by hadogenes** [comment]
I noticed that there was env variables and I thought that default file is the least demanding but the slowest. I had redis for my nextcloud so I'm reusing it

**Comment by stefanzweifel** [comment]
Alright. Most of the variables in the `.env`-file are coming from the default Laravel scaffold.

As it seems more and more people are using screeenly, I think it's best I update `.env.example` to only include the variables which are actually needed or should be changed.

As using redis in screeenly doesn't bring any benefit, I'm going to remove the redis configs and close your PR. 
`predis/predis` would still work in the current Laravel version screeenly uses, but as soon as we would upgrade to Laravel 6.0 we would have to remove it, as `predis` has been deprecated and is no longer recommended.

Hope that's okay for you.

**Comment by hadogenes** [comment]
OK, fine for me

**Comment by stefanzweifel** [comment]
The `.env.example` file has been updated in https://github.com/stefanzweifel/screeenly/commit/fb2bab013341cdfa953fa7a4ed0c053e5655cde6.
