### ISSUE TITLE
How to use this App

### ISSUE THREAD

**Issue by umardraz** [stefanzweifel/screeenly#336]
Hello how to use this App?

If this is pure PHP app then what is the document Root and what is the nginx or apache settings, or if this NodeJS app then how to run this and what will be the nodejs port?

**Comment by stefanzweifel** [comment]
Hi Umar,

This a PHP. A Laravel application to be precise.

After cloning the repo, it's best to follow [the official Laravel documentation](https://laravel.com/docs/5.8) on how to install and configure everything.

We also have a short – but probably not beginner friendly – [documentation](https://github.com/stefanzweifel/screeenly/wiki/Requirements-and-Install) on how to self host the app.

Regarding configuring a web server, please checkout [this documentation section](https://laravel.com/docs/5.8#configuration) about "Public Directory".

(The webserver must point to `public/index.php`)

**Comment by stefanzweifel** [comment]
I want to update the documentation soon, to be more beginner friendly and to make the app more accessible for more users.

**Comment by umardraz** [comment]
Thanks for you reply, I will look into it
