### ISSUE TITLE
Delay on taking screenshots

### ISSUE THREAD

**Issue by chrisbell08** [stefanzweifel/screeenly#36]
Hey, I've tried the online try it tool and when I try to screen shot my page: http://app.monstervsl.com/thumbnail?url=https://s3-us-west-2.amazonaws.com/monsterapps/monstervsl/videos/weightlossintro.mp4 I get a black screenshot. I assume this is because the video hasn't loaded when it takes the photo... Is there a fix for this? Can you add a delay variable so we can wait 2 seconds before taking it takes the screenshot?

**Comment by stefanzweifel** [comment]
Hey Chris

There's currently a delay of 1 second [built in](https://github.com/stefanzweifel/screeenly/blob/master/app/Screenshot/PhantomJsClient.php#L34).

I'm currently planing the future of this project and trying finishing up the V2 of the API. `delay` is on the list.

**Comment by chrisbell08** [comment]
Thanks for the quick reply. Do you no how far your away from releasing V2?

**Comment by stefanzweifel** [comment]
No release date yet. Sorry.

I refactored the core a few months ago. Routes [are setup](https://github.com/stefanzweifel/screeenly/blob/master/app/Http/routes.php#L69-L75). Will try to push the first "BETA" this weekend.

**Comment by chrisbell08** [comment]
ok np

**Comment by stefanzweifel** [comment]
Hey @chrisbell08 

Short update. I'm currently implementing an optional `delay` argument to the current API. But this doesn't seem to resolve your problem. Even on a 10 seconds delay Screeenly still generates a black image.

To generate those screenshots I use [PhantomJS](http://phantomjs.org/). This is headless browser powered by Javascript. Maybe PhantomJS can't display videos as you would like to.

I attached a screenshot of Youtube. Even here now image is displayed ...

![56acceb888d92bqtsyuwlxsvvfqvzuobj](https://cloud.githubusercontent.com/assets/1080923/12696404/6da616da-c76a-11e5-8df8-921a86ddeb41.jpg)

**Comment by chrisbell08** [comment]
Yeah the video element isn't supported in phantomjs I found this out last night when writing my own solution. What I've had to do is use wget to pull the video to my own server first, screenshot it with FFmpg then delete it.

**Comment by chrisbell08** [comment]
This might be handy : https://github.com/ariya/phantomjs/issues/10839

**Comment by sotonin** [comment]
I saw mention above of a delay param. did this ever make it in? I really need this due to the page being screenshotted not loading fully before the screenshot happens (not video related)

**Comment by stefanzweifel** [comment]
Yes. The Delay parameter is live! 
I forgot to document it. Will do this as soon as I'm back at my computer.

Here's the code with all parameters screeenly currently supports: https://github.com/stefanzweifel/screeenly/blob/master/modules/Screeenly/Http/Requests/CreateScreenshotRequest.php#L32

**Comment by stefanzweifel** [comment]
@sotonin I've updated [the wiki](https://github.com/stefanzweifel/screeenly/wiki/Use-the-API) with the delay option
