### ISSUE TITLE
Image size output

### ISSUE THREAD

**Issue by p-drolima** [stefanzweifel/screeenly#37]
Hi guys,

I am sorry if this as been mentioned before but I am not able to get image size to output to values I am specifying. Is there a limit on size?

Thanks

**Comment by stefanzweifel** [comment]
Hey

Do you have an example? A quick test with the following code returned a valid array.

```php
// $path can also be the path in your local filesystem
$path = "http://screeenly.com//images/generated/RSuVeWt4qNrxMbsXnxL0FP7e056af99cad1166.jpg";
$response = getimagesize($path);
```

Returns


````
array(7) {
  [0] => int(1024)
  [1] => int(3666)
  [2] => int(2)
  [3] => string(26) "width="1024" height="3666""
  ["bits"] => int(8)
  ["channels"] =>  int(3)
  ["mime"]=> string(10) "image/jpeg"
}
````

**Comment by p-drolima** [comment]
hi, nothing wrong with the output. I get that positive as well. what I meant is that when I put a value for width higher that 1024px I dont get that value in return

**Comment by p-drolima** [comment]
I understand you have to limit the size of files. and by the way big up for bring up such service open source ;)

**Comment by stefanzweifel** [comment]
How are you interacting with the API? Do you have an example?

**Comment by p-drolima** [comment]
`<?php

function screenly($objectURL) {

    $payload = array(
        'key' => '114bXWht4FD7xxgQuCPwdoKN9l8WEdHAuJd1J1qBoo8TYOKLlK',
        'url' => $objectURL,
        'height' => 768
    );
    $payload = json_encode($payload);
    $ch = curl_init('http://screeenly.com/api/v1/fullsize');
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/json',
                'Content-Length: ' . strlen($payload))
        );
    $result = curl_exec($ch);

    return $result;

}

?>`

**Comment by p-drolima** [comment]
that will give me 1024 width, but if i put a higher value, it wont give that but smaller value

**Comment by stefanzweifel** [comment]
The API defaults to a with of `1024px`. That's in my eyes a defacto-standard around the web. You can always override this value, by providing a `width` argument to the API.
So if you wan't a screenshot with a width of `1400px` you're request would look like this:


```php

<?php

function screenly($objectURL) {

    $payload = array(
        'key' => 'SECRET_KEY',
        'url' => $objectURL,
        'height' => 768,
        'width' => 1400
    );
    $payload = json_encode($payload);
    $ch = curl_init('http://screeenly.com/api/v1/fullsize');
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/json',
                'Content-Length: ' . strlen($payload))
        );
    $result = curl_exec($ch);

    return $result;

}

```

**Comment by p-drolima** [comment]
ok cool. thank a lot for your help

**Comment by stefanzweifel** [comment]
:+1:
