### ISSUE TITLE
install self hosted centos

### ISSUE THREAD

**Issue by Vromain** [stefanzweifel/screeenly#370]
After install when i try to take a screenshoot i have this message in red box

"Something went wrong capturing this website. Is it a Javascript heavy site or loads lots of external content? If you think this is an error contact us."

I juste need some help to find the problem because i don't find any log

**Comment by Vromain** [comment]
i find an another topic on this subject

**Comment by stefanzweifel** [comment]
Check the log in `storage/logs`. You should see more information on what is causing the error there.
