### ISSUE TITLE
bug of font spacing

### ISSUE THREAD

**Issue by mrbirddev** [stefanzweifel/screeenly#372]
https://3.screeenly.com/playground?data[url]=https%3A%2F%2Fdemo-76e69f00.slidde.co%2F&data[file_type]=jpg&data[window_width]=1440&data[window_height]=800&data[timeout]=10&data[css_media_type]=screen&data[full_page]=false&data[pdf_show_background]=false&data[show_browser_header_and_footer]=false&data[disable_javascript]=false&data[dismiss_dialogs]=false&data[wait_until_network_idle]=false&data[disable_web_security]=false&data[hide_background]=false&data[ignore_https_errors]=false&data[delay]=10000

![image](https://github.com/user-attachments/assets/dc66600c-187b-4837-a346-41a990242485)

https://demo-76e69f00.slidde.co/

I set the to delay to 10000ms. The animations are correct but the font spacing is buggy.

**Comment by stefanzweifel** [comment]
Hi @mrbirddev 

This repository is for issues regarding the open-source version of screeenly, that's currently available on the screeenly.com domain and which can be selfhosted on your own server.
The playground link you shared is about the paid-version of screeenly available on https://3.screeenly.com.

---

I can reproduce your issue. 
The issue might be related to a font that can not be loaded on the Linux machine, where the browser is booted that creates the screenshot. (Locally on macOS I can replicate the issue by changing the font to `"Apple Color Emoji"`.

I don't have a solution for this right now. This is also more related to the render-engine of the used browser and not to the PHP code in this repository.
Closing this issue for now.

**Comment by mrbirddev** [comment]
thank you for the quick response. does it mean if I self hsot and change the deploying machine the bug may disappear?

**Comment by stefanzweifel** [comment]
@mrbirddev Maybe. I can't confirm that right now. Under the hood, screeenly is _just_ a wrapper around [Puppeteer](https://pptr.dev/). 

You could install it in your own project and test the screenshot functionality yourself.
https://pptr.dev/guides/screenshots/
