### ISSUE TITLE
Security Issue: Accessing /etc/passwd

### ISSUE THREAD

**Issue by seelwerk** [stefanzweifel/screeenly#56]
Currently it is possible to read local files like `/etc/passwd` or other files (I did not iterate).

![image](https://cloud.githubusercontent.com/assets/13870666/15714467/e2aa1876-281a-11e6-950c-d6ecddff3c16.png)

Just insert `file:///etc/passwd` as Url and click on "Create Screenshot". I'm not going to add a screenshot of your /etc/passwd/ file here.

This will output the content of the `/etc/passwd` file since phantomJS is browsing it. The next Page will print out the content of the file and is Redirecting then to http://screeenly.com/try .
You should immediatly fix this issue

**Comment by stefanzweifel** [comment]
Thanks! Will look into this immediatly

**Comment by stefanzweifel** [comment]
Fixed! Thanks again @seelwerk 👍
