### ISSUE TITLE
Use a real browsers with Xvfb

### ISSUE THREAD

**Issue by klausenbusk** [stefanzweifel/screeenly#59]
Hello

Just wondering if you have considered using a real browser like Firefox or Chrome? (with Xvfb)

Most of all just a question, PhantomJS has always looked kind of unmaintained to me (no commits since 26 may and 1500+ issues).

Regards Kristian

**Comment by stefanzweifel** [comment]
Hey Kristian

I never considered using something else than PhantomJS for Screeenly, but I'm open for new technologies.

Will test it in the future.

(There's also something happening with a headless Chrome browser: https://twitter.com/samccone/status/739166801427210240)

**Comment by klausenbusk** [comment]
> (There's also something happening with a headless Chrome browser: https://twitter.com/samccone/status/739166801427210240)

Nice, in my research before this issue I stumbled on `moz-headless-screenshot`, but it was never merged it seems (https://bugzilla.mozilla.org/show_bug.cgi?id=headless).

In some older research I also stumbled on Selenium, which seems to be the perfect framework to use for taking screenshot.

Today I also stumbled on https://github.com/SeleniumHQ/docker-selenium , and Facebook has made a PHP framework to interact with Selenium (https://github.com/facebook/php-webdriver/wiki/Taking-Full-Screenshot-and-of-an-Element).

You could in theory combine it with docker-machine to get some sort of auto-scaling.


Now the big question is how it performance, (memory usage and how fast it can generate a screenshot). Running Firefox 45.0 currently (`selenium/standalone-firefox-debug:2.53.0`) which use 192MB which is much I think, not sure how fast Selenium can take a screenshot.

**Comment by klausenbusk** [comment]
So I did a little benchmark.

`docker run -t -i -p 4444:4444 -p 5900:5900 selenium/standalone-firefox-debug:2.53.0`

and the following python file:
```
from selenium import webdriver

driver = webdriver.Remote("http://localhost:4444/wd/hub", webdriver.DesiredCapabilities.FIREFOX.copy())
driver.get("http://www.google.com")
driver.get_screenshot_as_file('google.png')
driver.quit()
```

```
$ time python2 test.py 

real	0m5.970s
user	0m0.140s
sys	0m0.013s
```

It use a lot of the time to start Firefox, not sure how much time we save by "prestart" Firefox.
screeenly.com currently use 2 sec for the whole request, hm.

**Comment by klausenbusk** [comment]
More benchmark

```
import time
from selenium import webdriver

driver = webdriver.Remote("http://localhost:4444/wd/hub", webdriver.DesiredCapabilities.FIREFOX.copy())
start_time = time.time()
driver.get("http://www.google.com")
driver.get_screenshot_as_file('google.png')
driver.quit()

print("--- %s seconds ---" % (time.time() - start_time))
```

```
$ time python2 test.py 
--- 2.00333404541 seconds ---

real	0m6.207s
user	0m0.143s
sys	0m0.013s
```

2 seconds isn't bad, but then you need to have x Firefox instances running all time.

**Comment by stefanzweifel** [comment]
Thanks for your benchmarks!
I know screeenly isn't the fastest product out there. In my eyes it's still an early versions and it's still just a side project which runs on a small server.

As I said earlier, I will try to work on screeenly in the upcoming days / weeks. I really appreciate your work here and will try implementing it 😄.

**Comment by stefanzweifel** [comment]
[`node-webkit`](https://github.com/nwjs/nw.js) also looks like a good solution.

### Good Things:

- Easy to implement in node.js

```node
var screenshot = require('node-webkit-screenshot');
var url        = process.argv[2];

screenshot({
    url : url,
    width : 1024,
    height : 1000,
    delay: 1
})
.then(function(buffer) {
    screenshot.close(); // Close Process
    var base64Image = new Buffer(buffer, 'binary').toString('base64'); // Generate base64 Image
    console.log(base64Image); // Output to console
});
```

### Bad Things: 

- Can't generate screenshot for 100% height; only pixel values
- Can't set User Agent


### Things to consider

- How does it perform when many requests are coming in

**Comment by klausenbusk** [comment]
> node-webkit also looks like a good solution.

It also require Xvfb it seems https://github.com/nwjs/nw.js/issues/769 .. If we gonna run X anyways, I still think a regular browser is the most ideal, but up to you :)

**Comment by stefanzweifel** [comment]
I'm closing this issue for now.
I'm still aware that screeenly doesn't work on 100% of all websites but I would like to move on and work on other projects in the future.

I'm still watching / observing projects which do screeeshot generation. If an opportunity opens to implement a new Screenshot Driver which works all the time I will gladly implement it.
