### ISSUE TITLE
How can i set delay option ? (Add on parameters)

### ISSUE THREAD

**Issue by webhacking** [stefanzweifel/screeenly#84]
I checked [this](https://github.com/stefanzweifel/screeenly/wiki/Use-the-API#available-api-endpoints) document

But it is not working for me. I have added parameters like below.
Am i doing something wrong ?

e.g https://google.com?delay=10

**Comment by stefanzweifel** [comment]
Hi there,

The `delay` option has to be set in the payload you send to the API, not on the URL itself. I don't know how you send the request to screeenly.com so I've made this JSON example:

```json
{
    "key": "YOUR_API_KEY",
    "url": "http://google.com",
    "delay": 10
}
```

Does this work for you?

**Comment by webhacking** [comment]
@stefanzweifel Thanks. My bad

**Comment by bikker** [comment]
Hi, thank you for such a great script, but the delay is not working , i've set delay as per you told above  and using post to fullfill all these variables, other things all are working fine, width ,height , url , just delay is not .! 
`	$payload = array(
        "key" => 'API_KEY_HERE',
        "url" => $site,
	"delay" => $delay,
    // 'height' => $height, // Optional 
       "width" => $width
		// Optional
		);

    $payload = json_encode($payload);`

**Comment by stefanzweifel** [comment]
@bikker Thanks for reporting. I've justed fixed and deployed it in https://github.com/stefanzweifel/screeenly/commit/0fea53f31948ac723d66a3890fd2aa21952a5a4b.

It should now work as expected.

**Comment by bikker** [comment]
@stefanzweifel Thank you so much ! yes its now working , and what if i wanted delay to increase in my own self hosted system ,where can i change it to get max about 15-20 seconds.

**Comment by bikker** [comment]
@stefanzweifel  i changed it in Http/Requests/CreateScreenshotRequest.php to max 15 and its working till 15 now . 

Thank You !
